---
sudo: required
language: bash
matrix:
  include:
  - os: osx
    osx_image: xcode9.4 # macos 10.13 High Sierra
  - os: osx
    osx_image: xcode9.2 # macos 10.12 Sierra
  - os: osx
    osx_image: xcode8   # macos 10.11 El Capitan
  - os: osx
    osx_image: xcode6.4 # macos 10.10 Yosemite

#branches:
#  only:
#  - master
#  - /^\d+\.\d+(\.\d+)?(-\S*)?$/

before_install:
  # Remove the developer environment that travis installs by default - we need to ensure our script installs these things
  - brew cleanup
  - URL=https://raw.githubusercontent.com/Homebrew/install/master/uninstall
  - curl -sLO "${URL}"
  - chmod +x uninstall
  - ./uninstall --force
  - rm -rf /usr/local/Homebrew
  - sudo rm -rf /usr/local/Caskroom
  - sudo rm -rf /usr/local/bin/brew
  - sudo rm -rf /Library/Developer/CommandLineTools
  - sudo cat /etc/sudoers

install: false

script:

# Run the script:
- bash bin/strap run

# Run it again to check for idempotenence:
- bash bin/strap run
