---
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  vars:
    node_version: 8.11.1
    nvm_version: 0.33.11
    npm_version: 5.6.0
    nvm_dir: /root/.nvm
  become: yes
  tasks: 
  - name: Fetch Java version
    shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
    register: java_version

  - assert:
      that: 
        - java_version.stdout | version_compare('1.7', '>=')

  - name: Download the nvm(node version manager) install script
    shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh | bash

  - name: Delete previously nvm config
    shell: npm config delete prefix
    become_user: root

  - name: Register the NVM_DIR
    shell: cd /root && mkdir -p /root/.nvm && export NVM_DIR={{ nvm_dir }}
    become_user: root

  - name: Install the specified node version using the nvm command and set it as default
    shell: . {{ nvm_dir }}/nvm.sh && nvm install {{ node_version }} && nvm use {{ node_version }} && npm config set prefix=/root/.nvm/versions/node/v{{ node_version }}/bin && npm install npm@{{ npm_version }} -g --user "root" && nvm alias default {{ node_version }} && nvm use default
    become_user: root

  - name: Fetch npm version
    shell: npm -v
    register: npmVersion

  - name: Fetch node version
    shell: node -v
    register: nodeVersion

  - assert:
      that:
        - npmVersion.stdout | version_compare('{{ npm_version }}', '==')
        - nodeVersion.stdout | version_compare('v{{ node_version }}', '==')
